version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing Terraform...
      - curl -LO https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip
      - unzip terraform_1.8.2_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init
      - echo Validating Terraform...
      - terraform validate

  build:
    commands:
      - echo Running Terraform Plan...
      - terraform plan -out=tfplan.out

artifacts:
  files:
    - tfplan.out
